### ISSUE TITLE
Incompatibility with OpenPDF 3.0.0 – com.lowagie.text.DocumentException not found

### ISSUE THREAD

**Issue by kewinzielonka** [flyingsaucerproject/flyingsaucer#561]
After upgrading OpenPDF to 3.0.0, I’m encountering the following error when using ITextRenderer.createPDF with flying-saucer-pdf 9.13.3:

`class file for com.lowagie.text.DocumentException not found`

This happens because OpenPDF 3.0.0 has renamed the old com.lowagie.* package. The changelog states:

```
OpenPDF 3.0.0 uses the new package name org.openpdf.*. The old com.lowagie package is now removed from OpenPDF 3.0. This means that source code using OpenPDF must be migrated to use import statements with org.openpdf.*.
```
see [[OpenPDF 3.0.0 changelog](https://github.com/LibrePDF/OpenPDF/blob/master/changelogs/3.0.0.md)]

Currently, ITextRenderer imports the old class:

```
package org.xhtmlrenderer.pdf;

import com.lowagie.text.DocumentException;
```

Because of this, flying-saucer-pdf is not compatible with OpenPDF 3.0.0.

Steps to Reproduce:

Use flying-saucer-pdf:9.13.3

Upgrade OpenPDF to 3.0.0

Call ITextRenderer.createPDF(...)

Observe compilation error: class file for com.lowagie.text.DocumentException not found
